name: "build & deploy stg app"
on:
  push:

env:
  DEPLOY_SERVICE_ACCOUNT: github-oidc-deploy@g-map-flutter-432112.iam.gserviceaccount.com
  WORKLOAD_IDENTITY_PROVIDER: projects/679378251025/locations/global/workloadIdentityPools/g-map-flutter-432112-pool/providers/github-provider
  FIREBASE_APP_ID: g-map-flutter-432112

jobs:
  # analyze_and_test:
  #   uses: ./.github/workflows/ci.yml

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true
      - name: Setup packages
        run: |
          flutter pub get
      - name: Create key.properties
        run: |
          echo ${{ secrets.ANDROID_KEY_JKS }} | base64 -d > android/app/release.jks
          echo 'storeFile=release.jks' > android/key.properties
          echo 'storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}' >> android/key.properties
          echo 'keyPassword=${{ secrets.ANDROID_ALIAS_PASSWORD }}' >> android/key.properties
          echo 'keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}' >> android/key.properties
      - name: build
        run: flutter build appbundle --build-number=$GITHUB_RUN_NUMBER
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          service_account: ${{ env.DEPLOY_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
      - name: Setup Firebase Project
        run: curl -sL https://firebase.tools | bash
      - name: deploy firebase app distribution
        run: firebase build/app/outputs/bundle/release/app-release.aab --app $FIREBASE_APP_ID --groups developer
