name: analyze & test
on:
  push:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: setup repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.19.5"
      - name: check version
        run: flutter --version
      - name: Setup packages
        run: |
          flutter pub get
          dart run build_runner build -d
      - name: run analyze
        run: flutter analyze
      - name: run test
        run: flutter test
