name: "[ANDROID] build & deploy stg app"
on:
  push:
    branches: 
      - stg

jobs:
  analyze_and_test:
    name: Check test and analyze
    uses: ./.github/workflows/ci.yml

  build:
    name: Build Android
    needs: [analyze_and_test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true
      - name: Cache Flutter build
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            build/
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
      - name: Setup packages
        run: |
          flutter pub get
      - name: Create key.properties
        run: |
          echo ${{ secrets.ANDROID_KEY_JKS }} | base64 -d > android/app/release.jks
          echo 'storeFile=release.jks' > android/key.properties
          echo 'storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}' >> android/key.properties
          echo 'keyPassword=${{ secrets.ANDROID_ALIAS_PASSWORD }}' >> android/key.properties
          echo 'keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}' >> android/key.properties
      - name: build
        run: flutter build apk --build-number=$GITHUB_RUN_NUMBER
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          service_account: github-oidc-deploy@g-map-flutter-432112.iam.gserviceaccount.com
          workload_identity_provider: projects/679378251025/locations/global/workloadIdentityPools/g-map-flutter-432112-pool/providers/github-provider
      - name: Setup Firebase Project
        run: curl -sL https://firebase.tools | bash
      - name: deploy firebase app distribution
        env:
          ANDROID_APP_ID: ${{ secrets.ANDROID_APP_ID }}
        run: |
          firebase appdistribution:distribute \
          build/app/outputs/flutter-apk/app-release.apk \
          --app $ANDROID_APP_ID \
          --groups developer
